variable "region"  {}
variable "cidr_block"  {}
variable "subnets"  {}
variable "mgmt-1a"  {}
variable "mgmt-1b"  {}
variable "public-1a"  {}
variable "public-1b"  {}
variable "private-1a"  {}
variable "private-1b"  {}
variable "tgw-1a"  {}
variable "tgw-1b"  {}
variable "public_rts"  {}
